apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
spec:
  containers:
  - name: test
    image: nginxinc/nginx-unprivileged
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: true