version: "3.8"

services:
  uni-app-web:
    image: chandu554/duni:v1.1.0
    container_name: Retail-app123
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - uni-mongodb
    networks:
      - frontend-net
      - backend-net   # frontend joins both networks

  uni-mongodb:
    image: mysql:8.0
    container_name: mysql-cont123
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net   # backend only on backend-net

volumes:
  mysql_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

