version: "3.8"

services:
  uni-app-web:
    image: chandu554/duni:v1.1.0
    container_name: Retail-app12
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - uni-mongodb
    networks:
      - frontend-net
      - shared-net   # also connects to shared network to reach backend

  uni-mongodb:
    image: mysql:8.0
    container_name: mysql-cont12
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net
      - shared-net   # also connects to shared network to talk to frontend

volumes:
  mysql_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  shared-net:
    driver: bridge
