apiVersion: v1
kind: Secret
metadata:
  name: duni-sec
  namespace: chandana-ns 
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Root@123"
  MYSQLDB_USER: "college_user"
  MYSQLDB_PASSWORD: "deereddy@123"
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: duni-configmap 
  namespace: chandana-ns
data:
  DB_HOST: "mariadb"
  DB_PORT: "3306"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: duni-deploy 
  namespace: chandana-ns 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app: duni
  
  template: 
    metadata:
      labels:
        app: duni
    spec: 
      containers:
        - name: duni-cont 
          image: nimeshsv814/duniversity-portal:v1.1.0
          ports:
            - containerPort: 3001
          resources:
            requests: 
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: 
                  name: duni-configmap
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef: 
                  name: duni-configmap
                  key: DB_PORT
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_USER
            - name: MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_PASSWORD
           
          
            
---
apiVersion: v1 
kind: Service 
metadata:
  name: duni-ser 
  namespace: chandana-ns
spec:
  selector:
    app: duni 
  ports:
  - targetPort: 3000
    port: 3001
  type: ClusterIP