apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: duni-back
  namespace: chandana-ns 
spec:
  replicas: 3
  minReadySeconds: 10
  selector: 
    matchLabels:
      apps: uni
  
    
  template: 
    metadata:
      labels:
        apps: uni
    spec: 
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql-cont 
          image: mysql
          ports:
            - containerPort: 3306
          resources:
            requests: 
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_USER
            - name: MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-q
              mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-q
        configMap:
          name: mysql-init  
  volumeClaimTemplates:
  - metadata: # creating  pvc automatically no need of extra dynamicpvc file-no manual creation of pvc 
      name: mysql-storage
    spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-csi"
        resources:
          requests:
            storage: 2Gi
       # - name: mysql-storage
        #  persistentVolumeClaim:
        #    claimName: chandana-pvc 
        #- name: mysql-q
        #  configMap:
         #   name: mysql-init  
---
apiVersion: v1 
kind: Service 
metadata:
  name: mariadb
  namespace: chandana-ns
spec:
  selector:
    apps: uni 
  ports:
  - targetPort: 3306
    port: 3306
  type: ClusterIP
  clusterIP: None