apiVersion: v1

kind: Pod

metadata:

  name: nginx

spec:

  containers:

  - name: nginx

    image: nginx:latest
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    ports:

    - containerPort: 80

    resources:

      requests:

        memory: "256Mi"

        cpu: "100m"

      limits:

        memory: "512Mi"

        cpu: "200m"
  
 