apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: development-binding
  namespace: chandana-ns
subjects:
- kind: Group
  name: development
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: development-role
  apiGroup: rbac.authorization.k8s.io