app: 
  name: duni-deploy 
replicaCount: 2
image:
  repository: nimeshsv814/duniversity-portal
  tag: v1.1.0
ports:
  containerPort: 3000
backend:
  name: duni-back
  replicaCount: 1
  image: 
    backrepository: mysql
    backtag: latest
mysqlservice:
  name: mariadb
  port: 3306
  targetPort: 3306
frontendservice:
  name: duni-ser 
  port: 3001
  targetPort: 3000
configMap: 
  name: duni-configmap
  DBHOST: "mariadb"
  DBPORT: "3306"
  GRIEVANCEDB: "grievance_db"
  LEAVEDB: "leave_db"
  TIMETABLEDB: "timetable_db"
  EXAMSDB: "exams_db"