app: 
  name: duni-deploy 
replicaCount: 1
image:
  repository: nimeshsv814/duniversity-portal
  tag: v1.1.0
ports:
  containerPort: 3000
backend:
  name: duni-back
  replicaCount: 1
  image: 
    backrepository: mysql
    backtag: latest
mysqlservice:
  name: mariadb
  port: 3306
  targetPort: 3306
frontendservice:
  name: duni-ser 
  port: 3001
  targetPort: 3000
configMap: 
  name: duni-configmap
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  GRIEVANCE_DB: "grievance_db"
  LEAVE_DB: "leave_db"
  TIMETABLE_DB: "timetable_db"
  EXAMS_DB: "exams_db"