app: 
  name: duni-deploy 
replicaCount: 1
image:
  repository: nimeshsv814/duniversity-portal
  tag: v1.1.0
ports:
  containerPort: 3000
backend:
  name: duni-back
  replicaCount: 1
  image: 
    backrepository: mysql
    backtag: latest
mysqlservice:
  name: mariadb
  port: 3306
  targetPort: 3306