apiVersion: v1
kind: Secret
metadata:
  name: duni-sec
  namespace: chandana-ns 
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Um9vdEAxMjM=
  MYSQLDB_USER: Y29sbGVnZV91c2Vy
  MYSQLDB_PASSWORD: ZGVlcmVkZHlAMTIz

---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ .Values.configMap.name}} 
  namespace: chandana-ns
data:
  DB_HOST: "{{ .Values.configMap.DBHOST }}"
  DB_PORT: "{{ .Values.configMap.DBPORT }}"
  GRIEVANCE_DB: "{{ .Values.configMap.GRIEVANCEDB }}"
  LEAVE_DB: "{{ .Values.configMap.LEAVEDB }}" 
  TIMETABLE_DB: "{{ .Values.configMap.TIMETABLEDB }}" 
  EXAMS_DB: "{{ .Values.configMap.EXAMSDB }}"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.app.name }}
  namespace: chandana-ns 
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app: duni
  
  template: 
    metadata:
      labels:
        app: duni
    
     
    
    spec: 
      nodeSelector: 
        training: devops
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: training
      #           operator: In
      #           values:
                
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         - key: training
      #           operator: In
      #           values:
      #           - devops
      #     - weight: 50
      #       preference:
      #         matchExpressions:
      #         - key: training
      #           operator: In
      #           values:
      #           - devops 
      # affinity:
      #   podAffinity: #podAffinity if u want change it
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: apps
      #           operator: In
      #           values:
      #           - uni
      #       topologyKey: kubernetes.io/hostname
      tolerations: 
      - key: "training"
        operator: "Equal"
        value: "devlopment"
        effect: "NoExecute"
      containers:
        - name: duni-cont 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          resources:
            requests: 
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef: 
                  name: duni-configmap
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef: 
                  name: duni-configmap
                  key: DB_PORT
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_USER
            - name: MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: duni-sec
                  key: MYSQLDB_PASSWORD
           
          
            
---
apiVersion: v1 
kind: Service 
metadata:
  name:  {{.Values.frontendservice.name}}
  namespace: chandana-ns
spec:
  selector:
    app: duni 
  ports:
  - targetPort: {{ .Values.frontendservice.targetPort }}
    port: {{ .Values.frontendservice.port }}
  type: ClusterIP